.TH Ahorcado
.SH NAME
	El juego del ahorcado requiere de dos jugadores. Uno de ellos indicará
	la palabra del reto, y la otra persona tratará de adivinarla letra por
	letra. Se irá dibujando el ahorcado cada vez que se equivoque.Cuando 
	el dibujo esté completo, el juego finaliza y la persona pierde.
	Si adivina antes de terminar el ahorcado, la persona gana.
.SH SYNOPSIS
	


