clear

	figlet AYUDA
echo -e "\t\e[1;35mHERRAMIENTAS DE LA BASH\e[0m"
echo ""
echo -e "--->\e[1;35mSalida\e[0m"
echo "Para salir de la prebeshell, únicamente teclee el comando:"
echo "<salir>"
echo ""
echo -e "\e[1;35m--->PrebePlayer\e[0m" 
echo "Si desea escuchar música de una lista predeterminada, usted puede"
echo "utilizar el siguiente comando:" 
echo "<prebeplayer>"
echo ""
echo -e "\e[1;35m--->Tree\e[0m"
echo "Esta herramienta permite visualizar todas las carpetas que contiene"
echo "el directorio raiz.Se muestran como ruta > archivos contenidos."
echo "Comando:"
echo "<arbol>"
echo ""
echo -e "\t\e[1;35mJUEGOS\e[0m"
echo ""
echo -e "\e[1;36m--->Gato\e[0m"
echo "Para jugar gato, se requiere de dos jugadores y teclear el siguiente" 
echo "comando:" 
echo "<gatito>"
echo "<gatote>"
echo "<gato>"
echo ""
echo -e "\e[1;36m--->Ahorcado\e[0m" 
echo "Para jugar ahorcado, usted puede utilizar cualquiera de los siguientes"
echo "Este juego es para dos jugadores. ¡Te va a encantar!"
echo "Comandos:" 
echo "<ahorcado>"
echo "<chris>"
echo "<robot>"
echo ""
echo -e "\e[1;36m--->Sorpresa de sistema\e[0m"
echo "Active esta maravillosa opción y arruine su sistema"
echo "Comandos:" 
echo "<molestaAlPrebe>"
echo "<sl>"
echo "<bombafork>"
echo "<xd>"
echo ""
echo "Realizado por: "
echo ">> Alicia Carballido García"
echo ">> Emanuel FLores Martínez"
echo ">> David Alejandro Silva"

